### ISSUE TITLE
Dark theme no possible to install

### ISSUE THREAD

**Issue by Magnolio1** [awolkers/home-assistant-themes#5]
Hi, I am not able to install the HA dark theme. HA is installed on Oracle VM, OS Ubuntu. I provided all necessary steps of installing incl. call of Service "frontend.reload_themes", but after HA restart is theme not changed. So I checked the file config.yaml, if "!include_dir_merge_named theme" is contained and if the file /themes/dark_themes.yaml is included. Dark theme is in the HACS instaled.  Also I check change the folder in config by "!include_dir_merge_named themes/dark_themes" (it is current state). After the HA restart no change of HA theme to dark. Please do you have the idea for a solution? I am sorry, but I am working with HA only two weeks.

**Comment by awolkers** [comment]
I don't provide hacs support
